### ISSUE TITLE
'Argument not valid' after removing text

### ISSUE THREAD

**Issue by mniewrzal** [angelozerr/textmate.java#27] opened 2016-12-21 11:57 UTC
I have `java.lang.IllegalArgumentException: Argument not valid` when I'm working with PHP file colored with textmate4e. 

To reproduce:
* open/create file
```php
<?php

$aaa = new Test();
collator_get_|error_code()|
```
* delete text from between '|'

Stacktrace:
```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:9928)
	at org.eclipse.swt.custom.StyledText.replaceStyleRanges(StyledText.java:7911)
	at org.eclipse.jface.text.TextViewer.addPresentation(TextViewer.java:4692)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4769)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.applyTextRegionCollection(TMPresentationReconciler.java:426)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.colorize(TMPresentationReconciler.java:351)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler.access$4(TMPresentationReconciler.java:311)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:185)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2699)
	at org.eclipse.jface.text.TextViewer$VisibleDocumentListener.documentChanged(TextViewer.java:401)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:743)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:712)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:696)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:770)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1101)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.replace(SynchronizableDocument.java:173)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1119)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.replace(SynchronizableDocument.java:161)
	at org.eclipse.jface.text.DefaultDocumentAdapter.replaceTextRange(DefaultDocumentAdapter.java:233)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7350)
```
Version from master.

**Comment by angelozerr** [comment] 2016-12-21 21:03
I'm sorry @mniewrzal I cannot reproduce it:

![tm4ebug](https://cloud.githubusercontent.com/assets/1932211/21405956/59014168-c7c9-11e6-9f5c-7433c64ced1f.gif)

Please note that the main issue https://github.com/angelozerr/textmate.java/issues/5 should be fixed. Any contribution are welcome!

**Comment by mniewrzal** [comment] 2016-12-21 22:17
Sorry I think my description was to simple :)
![screencast from 12-21-2016 11-07-29 pm](https://cloud.githubusercontent.com/assets/7313031/21408140/9623c084-c7d3-11e6-947d-51122a00cc65.gif)

**Comment by angelozerr** [comment] 2016-12-22 08:02
Thnaks @mniewrzal for you demo! I can now reproduce your problem. The problem comes from #5 again

**Comment by angelozerr** [comment] 2016-12-22 17:22
@mniewrzal it should be fixed, please test and give me feedback. Thanks!

**Closed** 2016-12-22 17:21 UTC

**Comment by mniewrzal** [comment] 2016-12-23 09:37
Works without a problem right now :) Thanks!
